# architecture
arch: vit_base
enc_arch: ViTBackbone
dec_arch: UNETR_decoder

# wandb
proj_name: UNETR3D
run_name: unetr_(1-3)_dae_p158_mmd_penalty #unetr_full_dae_p158f0_mmd_penalty
wandb_id: 
disable_wandb: 1
wandb_proj: UNETR3D_p158

# dataset
dataset: prostate
# data_path: /data/leizhou/
task: Task2401_p158_prostate
data_path:  /home/dcampanini/datasets/ssl_prostate_data/nnUNet_raw_data/${task}
overviews_dir: /home/dcampanini/datasets/ssl_prostate_data/overviews/UNet/overviews/${task}
json_list: 'split0.json'
data_seed: 12345
augmentation_seeds: [0,1,2,3,4,5,6,7]
ts_fold: 0
ts_ratio: 0.
fold_id: 0

# outputs to save metrics when evaluating
metrics_dir: metrics/unetr/stage3_p158/unetr_full_dae_p158f4
save_roc_data: False # True mean save roc curve data
metrics_threshold: 0.5
# output
output_dir: /home/dcampanini/ssl_prostate_models_diego/mmd_penalty/unetr/p158/stage3/{run_name}
ckpt_dir: 


# data preprocessing
roi_x: 32
roi_y: 256
roi_z: 256
RandFlipd_prob: 0.2
RandRotate90d_prob: 0.2
RandScaleIntensityd_prob: 0.1
RandShiftIntensityd_prob: 0.1
infer_overlap: 0.5
spatial_dim: 3
cache_rate: 1.
num_samples: 1
image_shape: [32, 256, 256]
num_channels: 3

# trainer
trainer_name: SegTrainerMMD
batch_size: 2
val_batch_size: 1 # per gpu
use_test_augmentation: false
start_epoch: 0
warmup_epochs: 10
epochs: 40 # 200 original value, 40 new, 100 for scratch
workers: 8
num_threads: ${workers}
pretrain: /home/dcampanini/ssl_prostate_final_models/ssl_original/unetr/stage1/unetr_stage1_dae/ckpts/checkpoint_0299.pth.tar # para modelos (1,3)
resume:  # no se usa 
start_from: #/home/dcampanini/ssl_prostate_final_models/ssl_original/unetr/stage2/unetr_(1-2)_dae_picai_f0/ckpts/best_model.pth.tar # para modelos (2,3) ; (1,2,3);
save_intermediate: false
mmd_reference : /home/dcampanini/ssl_prostate_final_models/ssl_original/unetr/stage1/unetr_stage1_dae/ckpts/checkpoint_0299.pth.tar #/home/dcampanini/ssl_prostate_final_models/ssl_original/unetr/stage2/unetr_(1-2)_dae_picai_f0/ckpts/best_model.pth.tar


# drop
drop_path: 0.1
# tricks
mixup: 0.
cutmix: 0.
label_smoothing: 0.

# model
patch_size: 16
in_chans: 3
feature_size: 16
encoder_embed_dim: 768
encoder_depth: 12
encoder_num_heads: 12

# loss
smooth_nr: 0.0
smooth_dr: 1e-6

# mmd penalty parameters
mmd_weight: 100
mmd_sigma: 10000 # kernel sigma

# optimizer
type: adamw
lr: 0.011
beta1: 0.9
beta2: 0.95 #0.999
weight_decay: 0.1 #1e-5
layer_decay: 0.75
start_from_lr: 

# logging
# vis_freq: 100
vis_batch_size: 1
save_freq: 1
eval_freq: 1
print_freq: 1

# distributed processing
gpu: 0
dist_url: # 'tcp://localhost:10001'
world_size: 1
multiprocessing_distributed: false
dist_backend: nccl
distributed:
rank: 0
ngpus_per_node:

# randomness
seed: 5

# debugging
debug: false
manual_test: false
get_best_model: false
evaluate: false

num_classes: 2
out_chans: 2

# ensemble testing
eval_test: false
models_root_dir: 
models_to_ensemble: [] # Aqui deben ser los nombres de las run. Solo pueden ser del mismo tipo de arquitectura
metrics_save_path:  